"""add subject_mapping to calendar_sources

Revision ID: 78445b9799f6
Revises: 1bc5d6be88da
Create Date: 2026-02-13 14:11:44.173333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78445b9799f6'
down_revision: Union[str, Sequence[str], None] = '1bc5d6be88da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_sources', sa.Column('subject_mapping', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_sources', 'subject_mapping')
    # ### end Alembic commands ###
