"""Add reminder fields

Revision ID: a1e087e3aeae
Revises: a9fcb80fc748
Create Date: 2026-02-24 16:50:00.968563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e087e3aeae'
down_revision: Union[str, Sequence[str], None] = 'a9fcb80fc748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('tasks', sa.Column('sent_reminders', sa.JSON(), nullable=True))
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('users', sa.Column('reminder_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reminder_preferences')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'sent_reminders')
    op.alter_column('subjects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
