"""refactor_relations_drop_telegram_id

Revision ID: a9fcb80fc748
Revises: 939bc8544a3f
Create Date: 2026-02-15 17:03:15.848216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9fcb80fc748'
down_revision: Union[str, Sequence[str], None] = '939bc8544a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'calendar_sources', 'users', ['user_id'], ['id'])
    
    # --- Subjects Migration ---
    op.add_column('subjects', sa.Column('user_id', sa.Integer(), nullable=True))
    # Data migration for subjects
    op.execute("""
        UPDATE subjects 
        SET user_id = users.id 
        FROM users 
        WHERE subjects.telegram_id = users.telegram_id
    """)
    op.alter_column('subjects', 'user_id', nullable=False) # Enforce non-null after population
    
    op.drop_index(op.f('ix_subjects_telegram_id'), table_name='subjects')
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'users', ['user_id'], ['id'])
    op.drop_column('subjects', 'telegram_id')
    
    # --- Tasks Migration ---
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    # Data migration for tasks
    op.execute("""
        UPDATE tasks 
        SET user_id = users.id 
        FROM users 
        WHERE tasks.telegram_id = users.telegram_id
    """)
    # Note: If there are tasks without a matching user (orphan data), this might fail if we enforce nullable=False.
    # We will enforce it, assuming data integrity or that orphans are acceptable to fail/we should delete them? 
    # For now, let's enforce it as per requirements.
    op.execute("DELETE FROM tasks WHERE user_id IS NULL") # Clean up orphans if any
    op.alter_column('tasks', 'user_id', nullable=False)

    op.drop_index(op.f('ix_tasks_telegram_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'calendar_sources', ['calendar_source_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.drop_column('tasks', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_telegram_id'), 'tasks', ['telegram_id'], unique=False)
    op.drop_column('tasks', 'user_id')
    op.add_column('subjects', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.create_index(op.f('ix_subjects_telegram_id'), 'subjects', ['telegram_id'], unique=False)
    op.drop_column('subjects', 'user_id')
    op.drop_constraint(None, 'calendar_sources', type_='foreignkey')
    # ### end Alembic commands ###
